/**
 * Generated by the Supabase MCP `generate_typescript_types` for project
 * PANTAS (saipqorcjeizxizjpfsp). Regenerate after schema migrations:
 * `npx supabase gen types typescript --project-id saipqorcjeizxizjpfsp`.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      gradings: {
        Row: {
          created_at: string;
          gambar_url: string | null;
          grade_dominan: string;
          hash_audit: string | null;
          hasil: Json;
          id: string;
          komoditas: string;
          komoditas_label: string;
          objek_terdeteksi: number;
          petani_id: string;
        };
        Insert: {
          created_at?: string;
          gambar_url?: string | null;
          grade_dominan: string;
          hash_audit?: string | null;
          hasil: Json;
          id?: string;
          komoditas: string;
          komoditas_label: string;
          objek_terdeteksi?: number;
          petani_id: string;
        };
        Update: {
          created_at?: string;
          gambar_url?: string | null;
          grade_dominan?: string;
          hash_audit?: string | null;
          hasil?: Json;
          id?: string;
          komoditas?: string;
          komoditas_label?: string;
          objek_terdeteksi?: number;
          petani_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "gradings_petani_id_fkey";
            columns: ["petani_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      harga_acuan: {
        Row: {
          harga: number;
          komoditas: string;
          label: string;
          sumber: string;
          updated_at: string;
        };
        Insert: {
          harga: number;
          komoditas: string;
          label: string;
          sumber?: string;
          updated_at?: string;
        };
        Update: {
          harga?: number;
          komoditas?: string;
          label?: string;
          sumber?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      listings: {
        Row: {
          berat_kg: number;
          catatan_ai: string | null;
          created_at: string;
          gambar: string;
          grade: string;
          grading_id: string | null;
          harga_per_kg: number;
          id: string;
          komoditas: string;
          komposisi: Json | null;
          nama: string;
          panen_terakhir: string | null;
          petani_id: string;
          satuan: string | null;
          status: string;
          stok_kg: number | null;
        };
        Insert: {
          berat_kg: number;
          catatan_ai?: string | null;
          created_at?: string;
          gambar?: string;
          grade: string;
          grading_id?: string | null;
          harga_per_kg: number;
          id?: string;
          komoditas: string;
          komposisi?: Json | null;
          nama: string;
          panen_terakhir?: string | null;
          petani_id: string;
          satuan?: string | null;
          status?: string;
          stok_kg?: number | null;
        };
        Update: {
          berat_kg?: number;
          catatan_ai?: string | null;
          created_at?: string;
          gambar?: string;
          grade?: string;
          grading_id?: string | null;
          harga_per_kg?: number;
          id?: string;
          komoditas?: string;
          komposisi?: Json | null;
          nama?: string;
          panen_terakhir?: string | null;
          petani_id?: string;
          satuan?: string | null;
          status?: string;
          stok_kg?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "listings_grading_id_fkey";
            columns: ["grading_id"];
            isOneToOne: false;
            referencedRelation: "gradings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "listings_petani_id_fkey";
            columns: ["petani_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          berat_aktual_kg: number | null;
          berat_kg: number;
          created_at: string;
          grade: string;
          harga_per_kg: number;
          id: string;
          kode: string;
          listing_id: string | null;
          nama: string;
          pembeli_id: string;
          petani_id: string;
          status: string;
          total: number;
        };
        Insert: {
          berat_aktual_kg?: number | null;
          berat_kg: number;
          created_at?: string;
          grade: string;
          harga_per_kg: number;
          id?: string;
          kode?: string;
          listing_id?: string | null;
          nama: string;
          pembeli_id: string;
          petani_id: string;
          status?: string;
          total: number;
        };
        Update: {
          berat_aktual_kg?: number | null;
          berat_kg?: number;
          created_at?: string;
          grade?: string;
          harga_per_kg?: number;
          id?: string;
          kode?: string;
          listing_id?: string | null;
          nama?: string;
          pembeli_id?: string;
          petani_id?: string;
          status?: string;
          total?: number;
        };
        Relationships: [
          {
            foreignKeyName: "orders_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: false;
            referencedRelation: "listings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: false;
            referencedRelation: "listings_view";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_pembeli_id_fkey";
            columns: ["pembeli_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_petani_id_fkey";
            columns: ["petani_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          alamat: string | null;
          created_at: string;
          id: string;
          lat: number | null;
          lng: number | null;
          lokasi: string | null;
          nama: string;
          peran: string;
          phone: string | null;
          rating: number;
          transaksi: number;
          tur_selesai?: boolean;
        };
        Insert: {
          alamat?: string | null;
          created_at?: string;
          id: string;
          lat?: number | null;
          lng?: number | null;
          lokasi?: string | null;
          nama: string;
          peran: string;
          phone?: string | null;
          rating?: number;
          transaksi?: number;
          tur_selesai?: boolean;
        };
        Update: {
          alamat?: string | null;
          created_at?: string;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          lokasi?: string | null;
          nama?: string;
          peran?: string;
          phone?: string | null;
          rating?: number;
          transaksi?: number;
          tur_selesai?: boolean;
        };
        Relationships: [];
      };
      ulasan: {
        Row: {
          id: string;
          order_id: string;
          penilai_id: string;
          dinilai_id: string;
          bintang: number;
          komentar: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          penilai_id: string;
          dinilai_id: string;
          bintang: number;
          komentar?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          penilai_id?: string;
          dinilai_id?: string;
          bintang?: number;
          komentar?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      penawaran: {
        Row: {
          id: string;
          listing_id: string;
          pembeli_id: string;
          petani_id: string;
          kuantitas_kg: number;
          harga_per_kg: number;
          tanggal_ambil: string | null;
          catatan: string | null;
          status: string;
          induk_id: string | null;
          kedaluwarsa_pada: string;
          created_at: string;
          /**
           * Pesanan yang lahir dari penawaran ini (migrasi 0017). Hanya
           * `terima_penawaran()` yang menulisnya — klien tidak punya hak
           * update pada kolom ini.
           */
          order_id: string | null;
        };
        Insert: {
          id?: string;
          listing_id: string;
          pembeli_id: string;
          petani_id: string;
          kuantitas_kg: number;
          harga_per_kg: number;
          tanggal_ambil?: string | null;
          catatan?: string | null;
          status?: string;
          induk_id?: string | null;
          kedaluwarsa_pada?: string;
          created_at?: string;
        };
        /** Hanya `status` dan `harga_per_kg` yang di-grant ke `authenticated`. */
        Update: {
          status?: string;
          harga_per_kg?: number;
        };
        Relationships: [
          {
            foreignKeyName: "penawaran_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: false;
            referencedRelation: "listings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "penawaran_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "penawaran_pembeli_id_fkey";
            columns: ["pembeli_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "penawaran_petani_id_fkey";
            columns: ["petani_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      pesan: {
        Row: {
          id: string;
          order_id: string | null;
          penawaran_id: string | null;
          pengirim_id: string;
          penerima_id: string;
          isi: string;
          dibaca: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          penawaran_id?: string | null;
          pengirim_id: string;
          penerima_id: string;
          isi: string;
          dibaca?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          penawaran_id?: string | null;
          pengirim_id?: string;
          penerima_id?: string;
          isi?: string;
          dibaca?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      densitas_kalibrasi_view: {
        Row: {
          berat_aktual_kg: number | null;
          gram_per_mm2: number | null;
          komoditas: string | null;
          komoditas_dasar: string | null;
          luas_mm2: number | null;
          objek_terdeteksi: number | null;
          order_id: string | null;
          tanggal: string | null;
        };
        Relationships: [];
      };
      listings_view: {
        Row: {
          alamat: string | null;
          berat_kg: number | null;
          catatan_ai: string | null;
          created_at: string | null;
          gambar: string | null;
          grade: string | null;
          grading_id: string | null;
          harga_per_kg: number | null;
          hash_audit: string | null;
          id: string | null;
          komoditas: string | null;
          komposisi: Json | null;
          lat: number | null;
          lng: number | null;
          lokasi: string | null;
          nama: string | null;
          panen_terakhir: string | null;
          petani: string | null;
          petani_id: string | null;
          rating: number | null;
          satuan: string | null;
          status: string | null;
          stok_kg: number | null;
          transaksi: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "listings_grading_id_fkey";
            columns: ["grading_id"];
            isOneToOne: false;
            referencedRelation: "gradings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "listings_petani_id_fkey";
            columns: ["petani_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      gen_kode_serah_terima: { Args: never; Returns: string };
      /**
       * Menerima penawaran dan menerbitkan pesanannya dalam satu transaksi
       * (migrasi 0017). Mengembalikan baris `orders` yang lahir — atau yang
       * sudah ada, bila penawarannya pernah diterima sebelumnya.
       */
      terima_penawaran: {
        Args: { p_penawaran_id: string; p_harga_per_kg?: number | null };
        Returns: Database["public"]["Tables"]["orders"]["Row"];
      };
      verifikasi_serah_terima: {
        Args: {
          p_berat_aktual_kg?: number | null;
          p_kode: string;
          p_order_id: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
