/**
 * Generated by Supabase MCP `generate_typescript_types` for project PANTAS (saipqorcjeizxizjpfsp).
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.17"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          aksi: string
          aktor_id: string | null
          created_at: string
          entitas: string
          entitas_id: string | null
          id: number
          meta: Json | null
        }
        Insert: {
          aksi: string
          aktor_id?: string | null
          created_at?: string
          entitas: string
          entitas_id?: string | null
          id?: number
          meta?: Json | null
        }
        Update: {
          aksi?: string
          aktor_id?: string | null
          created_at?: string
          entitas?: string
          entitas_id?: string | null
          id?: number
          meta?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_aktor_id_fkey"
            columns: ["aktor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      emisi_faktor: {
        Row: {
          catatan: string | null
          faktor: number
          komoditas: string
          satuan: string
          sumber: string
        }
        Insert: {
          catatan?: string | null
          faktor: number
          komoditas: string
          satuan?: string
          sumber: string
        }
        Update: {
          catatan?: string | null
          faktor?: number
          komoditas?: string
          satuan?: string
          sumber?: string
        }
        Relationships: []
      }
      gradings: {
        Row: {
          created_at: string
          gambar_url: string | null
          grade_dominan: string
          hash_audit: string | null
          hasil: Json
          id: string
          komoditas: string
          komoditas_label: string
          objek_terdeteksi: number
          petani_id: string
        }
        Insert: {
          created_at?: string
          gambar_url?: string | null
          grade_dominan: string
          hash_audit?: string | null
          hasil: Json
          id?: string
          komoditas: string
          komoditas_label: string
          objek_terdeteksi?: number
          petani_id: string
        }
        Update: {
          created_at?: string
          gambar_url?: string | null
          grade_dominan?: string
          hash_audit?: string | null
          hasil?: Json
          id?: string
          komoditas?: string
          komoditas_label?: string
          objek_terdeteksi?: number
          petani_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "gradings_petani_id_fkey"
            columns: ["petani_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      harga_acuan: {
        Row: {
          harga: number
          komoditas: string
          label: string
          sumber: string
          updated_at: string
        }
        Insert: {
          harga: number
          komoditas: string
          label: string
          sumber?: string
          updated_at?: string
        }
        Update: {
          harga?: number
          komoditas?: string
          label?: string
          sumber?: string
          updated_at?: string
        }
        Relationships: []
      }
      listings: {
        Row: {
          berat_kg: number
          catatan_ai: string | null
          created_at: string
          gambar: string
          grade: string
          grading_id: string | null
          harga_per_kg: number
          id: string
          komoditas: string
          komposisi: Json | null
          nama: string
          panen_terakhir: string | null
          petani_id: string
          satuan: string | null
          status: string
          stok_kg: number | null
        }
        Insert: {
          berat_kg: number
          catatan_ai?: string | null
          created_at?: string
          gambar?: string
          grade: string
          grading_id?: string | null
          harga_per_kg: number
          id?: string
          komoditas: string
          komposisi?: Json | null
          nama: string
          panen_terakhir?: string | null
          petani_id: string
          satuan?: string | null
          status?: string
          stok_kg?: number | null
        }
        Update: {
          berat_kg?: number
          catatan_ai?: string | null
          created_at?: string
          gambar?: string
          grade?: string
          grading_id?: string | null
          harga_per_kg?: number
          id?: string
          komoditas?: string
          komposisi?: Json | null
          nama?: string
          panen_terakhir?: string | null
          petani_id?: string
          satuan?: string | null
          status?: string
          stok_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "listings_grading_id_fkey"
            columns: ["grading_id"]
            isOneToOne: false
            referencedRelation: "gradings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_petani_id_fkey"
            columns: ["petani_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      order_kode: {
        Row: {
          dipakai_pada: string | null
          kode: string
          order_id: string
        }
        Insert: {
          dipakai_pada?: string | null
          kode: string
          order_id: string
        }
        Update: {
          dipakai_pada?: string | null
          kode?: string
          order_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_kode_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "densitas_kalibrasi_view"
            referencedColumns: ["order_id"]
          },
          {
            foreignKeyName: "order_kode_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          alasan_kasus: string | null
          berat_aktual_kg: number | null
          berat_kg: number
          created_at: string
          diminta_oleh: string | null
          diminta_pada: string | null
          ditanggapi_oleh: string | null
          ditanggapi_pada: string | null
          grade: string
          harga_per_kg: number
          id: string
          kode: string
          listing_id: string | null
          nama: string
          pembayaran_dikonfirmasi_pada: string | null
          pembayaran_ditandai_pada: string | null
          pembeli_id: string
          petani_id: string
          status: string
          status_kasus: string
          status_pembayaran: string
          total: number
        }
        Insert: {
          alasan_kasus?: string | null
          berat_aktual_kg?: number | null
          berat_kg: number
          created_at?: string
          diminta_oleh?: string | null
          diminta_pada?: string | null
          ditanggapi_oleh?: string | null
          ditanggapi_pada?: string | null
          grade: string
          harga_per_kg: number
          id?: string
          kode?: string
          listing_id?: string | null
          nama: string
          pembayaran_dikonfirmasi_pada?: string | null
          pembayaran_ditandai_pada?: string | null
          pembeli_id: string
          petani_id: string
          status?: string
          status_kasus?: string
          status_pembayaran?: string
          total: number
        }
        Update: {
          alasan_kasus?: string | null
          berat_aktual_kg?: number | null
          berat_kg?: number
          created_at?: string
          diminta_oleh?: string | null
          diminta_pada?: string | null
          ditanggapi_oleh?: string | null
          ditanggapi_pada?: string | null
          grade?: string
          harga_per_kg?: number
          id?: string
          kode?: string
          listing_id?: string | null
          nama?: string
          pembayaran_dikonfirmasi_pada?: string | null
          pembayaran_ditandai_pada?: string | null
          pembeli_id?: string
          petani_id?: string
          status?: string
          status_kasus?: string
          status_pembayaran?: string
          total?: number
        }
        Relationships: [
          {
            foreignKeyName: "orders_diminta_oleh_fkey"
            columns: ["diminta_oleh"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_ditanggapi_oleh_fkey"
            columns: ["ditanggapi_oleh"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings_view"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_pembeli_id_fkey"
            columns: ["pembeli_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_petani_id_fkey"
            columns: ["petani_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      penawaran: {
        Row: {
          catatan: string | null
          created_at: string
          harga_per_kg: number
          id: string
          induk_id: string | null
          kedaluwarsa_pada: string
          kuantitas_kg: number
          listing_id: string
          order_id: string | null
          pembeli_id: string
          petani_id: string
          status: string
          tanggal_ambil: string | null
        }
        Insert: {
          catatan?: string | null
          created_at?: string
          harga_per_kg: number
          id?: string
          induk_id?: string | null
          kedaluwarsa_pada?: string
          kuantitas_kg: number
          listing_id: string
          order_id?: string | null
          pembeli_id: string
          petani_id: string
          status?: string
          tanggal_ambil?: string | null
        }
        Update: {
          catatan?: string | null
          created_at?: string
          harga_per_kg?: number
          id?: string
          induk_id?: string | null
          kedaluwarsa_pada?: string
          kuantitas_kg?: number
          listing_id?: string
          order_id?: string | null
          pembeli_id?: string
          petani_id?: string
          status?: string
          tanggal_ambil?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "penawaran_induk_id_fkey"
            columns: ["induk_id"]
            isOneToOne: false
            referencedRelation: "penawaran"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "penawaran_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "penawaran_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings_view"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "penawaran_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "densitas_kalibrasi_view"
            referencedColumns: ["order_id"]
          },
          {
            foreignKeyName: "penawaran_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "penawaran_pembeli_id_fkey"
            columns: ["pembeli_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "penawaran_petani_id_fkey"
            columns: ["petani_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pengiriman: {
        Row: {
          alamat_jemput: string | null
          catatan: string | null
          checklist: Json | null
          created_at: string
          id: string
          jendela_mulai: string | null
          jendela_selesai: string | null
          lat: number | null
          lng: number | null
          metode: string
          ongkos_estimasi: number | null
          order_id: string
          status: string
        }
        Insert: {
          alamat_jemput?: string | null
          catatan?: string | null
          checklist?: Json | null
          created_at?: string
          id?: string
          jendela_mulai?: string | null
          jendela_selesai?: string | null
          lat?: number | null
          lng?: number | null
          metode?: string
          ongkos_estimasi?: number | null
          order_id: string
          status?: string
        }
        Update: {
          alamat_jemput?: string | null
          catatan?: string | null
          checklist?: Json | null
          created_at?: string
          id?: string
          jendela_mulai?: string | null
          jendela_selesai?: string | null
          lat?: number | null
          lng?: number | null
          metode?: string
          ongkos_estimasi?: number | null
          order_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "pengiriman_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "densitas_kalibrasi_view"
            referencedColumns: ["order_id"]
          },
          {
            foreignKeyName: "pengiriman_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      pesan: {
        Row: {
          created_at: string
          dibaca: boolean
          id: string
          isi: string
          order_id: string | null
          penawaran_id: string | null
          penerima_id: string
          pengirim_id: string
        }
        Insert: {
          created_at?: string
          dibaca?: boolean
          id?: string
          isi: string
          order_id?: string | null
          penawaran_id?: string | null
          penerima_id: string
          pengirim_id: string
        }
        Update: {
          created_at?: string
          dibaca?: boolean
          id?: string
          isi?: string
          order_id?: string | null
          penawaran_id?: string | null
          penerima_id?: string
          pengirim_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pesan_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "densitas_kalibrasi_view"
            referencedColumns: ["order_id"]
          },
          {
            foreignKeyName: "pesan_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pesan_penawaran_id_fkey"
            columns: ["penawaran_id"]
            isOneToOne: false
            referencedRelation: "penawaran"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pesan_penerima_id_fkey"
            columns: ["penerima_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pesan_pengirim_id_fkey"
            columns: ["pengirim_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pesanan_riwayat: {
        Row: {
          catatan: string | null
          created_at: string
          id: number
          oleh: string | null
          order_id: string
          status: string
        }
        Insert: {
          catatan?: string | null
          created_at?: string
          id?: number
          oleh?: string | null
          order_id: string
          status: string
        }
        Update: {
          catatan?: string | null
          created_at?: string
          id?: number
          oleh?: string | null
          order_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "pesanan_riwayat_oleh_fkey"
            columns: ["oleh"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pesanan_riwayat_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "densitas_kalibrasi_view"
            referencedColumns: ["order_id"]
          },
          {
            foreignKeyName: "pesanan_riwayat_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          alamat: string | null
          created_at: string
          id: string
          is_demo: boolean
          lat: number | null
          lng: number | null
          lokasi: string | null
          nama: string
          peran: string
          phone: string | null
          rating: number
          transaksi: number
          tur_selesai: boolean
        }
        Insert: {
          alamat?: string | null
          created_at?: string
          id: string
          is_demo?: boolean
          lat?: number | null
          lng?: number | null
          lokasi?: string | null
          nama: string
          peran: string
          phone?: string | null
          rating?: number
          transaksi?: number
          tur_selesai?: boolean
        }
        Update: {
          alamat?: string | null
          created_at?: string
          id?: string
          is_demo?: boolean
          lat?: number | null
          lng?: number | null
          lokasi?: string | null
          nama?: string
          peran?: string
          phone?: string | null
          rating?: number
          transaksi?: number
          tur_selesai?: boolean
        }
        Relationships: []
      }
      rute: {
        Row: {
          created_at: string
          dibuat_oleh: string | null
          id: string
          jarak_individual_km: number | null
          jarak_km: number | null
          kapasitas_kg: number | null
          kendaraan: string | null
          nomor: number
          status: string
          tanggal: string
        }
        Insert: {
          created_at?: string
          dibuat_oleh?: string | null
          id?: string
          jarak_individual_km?: number | null
          jarak_km?: number | null
          kapasitas_kg?: number | null
          kendaraan?: string | null
          nomor?: number
          status?: string
          tanggal?: string
        }
        Update: {
          created_at?: string
          dibuat_oleh?: string | null
          id?: string
          jarak_individual_km?: number | null
          jarak_km?: number | null
          kapasitas_kg?: number | null
          kendaraan?: string | null
          nomor?: number
          status?: string
          tanggal?: string
        }
        Relationships: [
          {
            foreignKeyName: "rute_dibuat_oleh_fkey"
            columns: ["dibuat_oleh"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      rute_item: {
        Row: {
          pengiriman_id: string
          perkiraan_tiba: string | null
          rute_id: string
          urutan: number
        }
        Insert: {
          pengiriman_id: string
          perkiraan_tiba?: string | null
          rute_id: string
          urutan: number
        }
        Update: {
          pengiriman_id?: string
          perkiraan_tiba?: string | null
          rute_id?: string
          urutan?: number
        }
        Relationships: [
          {
            foreignKeyName: "rute_item_pengiriman_id_fkey"
            columns: ["pengiriman_id"]
            isOneToOne: false
            referencedRelation: "pengiriman"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rute_item_rute_id_fkey"
            columns: ["rute_id"]
            isOneToOne: false
            referencedRelation: "rute"
            referencedColumns: ["id"]
          },
        ]
      }
      ulasan: {
        Row: {
          bintang: number
          created_at: string
          dinilai_id: string
          id: string
          komentar: string | null
          order_id: string
          penilai_id: string
        }
        Insert: {
          bintang: number
          created_at?: string
          dinilai_id: string
          id?: string
          komentar?: string | null
          order_id: string
          penilai_id: string
        }
        Update: {
          bintang?: number
          created_at?: string
          dinilai_id?: string
          id?: string
          komentar?: string | null
          order_id?: string
          penilai_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ulasan_dinilai_id_fkey"
            columns: ["dinilai_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ulasan_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "densitas_kalibrasi_view"
            referencedColumns: ["order_id"]
          },
          {
            foreignKeyName: "ulasan_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ulasan_penilai_id_fkey"
            columns: ["penilai_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      dampak_agregat: {
        Row: {
          kg_tersalurkan: number | null
          km_dihemat: number | null
          nilai_transaksi: number | null
          transaksi_selesai: number | null
        }
        Relationships: []
      }
      densitas_kalibrasi_view: {
        Row: {
          berat_aktual_kg: number | null
          gram_per_mm2: number | null
          komoditas: string | null
          komoditas_dasar: string | null
          luas_mm2: number | null
          objek_terdeteksi: number | null
          order_id: string | null
          tanggal: string | null
        }
        Relationships: []
      }
      listings_view: {
        Row: {
          alamat: string | null
          berat_kg: number | null
          catatan_ai: string | null
          created_at: string | null
          gambar: string | null
          grade: string | null
          grading_id: string | null
          harga_per_kg: number | null
          hash_audit: string | null
          id: string | null
          komoditas: string | null
          komposisi: Json | null
          lat: number | null
          lng: number | null
          lokasi: string | null
          nama: string | null
          panen_terakhir: string | null
          petani: string | null
          petani_id: string | null
          rating: number | null
          satuan: string | null
          status: string | null
          stok_kg: number | null
          transaksi: number | null
        }
        Relationships: [
          {
            foreignKeyName: "listings_grading_id_fkey"
            columns: ["grading_id"]
            isOneToOne: false
            referencedRelation: "gradings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_petani_id_fkey"
            columns: ["petani_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      ajukan_pembatalan_order: {
        Args: { p_alasan: string; p_order_id: string }
        Returns: Json
      }
      boleh_menilai_pesanan: {
        Args: { p_dinilai_id: string; p_order_id: string; p_penilai_id: string }
        Returns: boolean
      }
      gen_kode_serah_terima: { Args: never; Returns: string }
      is_admin: { Args: never; Returns: boolean }
      buka_sengketa_order: {
        Args: { p_alasan: string; p_order_id: string }
        Returns: Json
      }
      konfirmasi_pembayaran_order: {
        Args: { p_order_id: string }
        Returns: Json
      }
      moderasi_listing: {
        Args: { p_alasan: string; p_listing_id: string; p_status: string }
        Returns: string
      }
      reset_demo: { Args: never; Returns: Json }
      selesaikan_sengketa_order: {
        Args: { p_batalkan: boolean; p_catatan: string; p_order_id: string }
        Returns: Json
      }
      tandai_pembayaran_order: {
        Args: { p_order_id: string }
        Returns: Json
      }
      tanggapi_pembatalan_order: {
        Args: { p_order_id: string; p_setuju: boolean }
        Returns: Json
      }
      terima_penawaran: {
        Args: { p_harga_per_kg?: number; p_penawaran_id: string }
        Returns: {
          alasan_kasus: string | null
          berat_aktual_kg: number | null
          berat_kg: number
          created_at: string
          diminta_oleh: string | null
          diminta_pada: string | null
          ditanggapi_oleh: string | null
          ditanggapi_pada: string | null
          grade: string
          harga_per_kg: number
          id: string
          kode: string
          listing_id: string | null
          nama: string
          pembayaran_dikonfirmasi_pada: string | null
          pembayaran_ditandai_pada: string | null
          pembeli_id: string
          petani_id: string
          status: string
          status_kasus: string
          status_pembayaran: string
          total: number
        }
        SetofOptions: {
          from: "*"
          to: "orders"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      ubah_status_rute: {
        Args: { p_rute_id: string; p_status: string }
        Returns: string
      }
      urutan_status_pesanan: { Args: { s: string }; Returns: number }
      verifikasi_serah_terima: {
        Args: { p_berat_aktual_kg?: number; p_kode: string; p_order_id: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never
