// AUTO-GENERATED by scripts/gen-komoditas.mjs — do NOT edit by hand.
// Source of truth: ai_engine/grading_configs/*.json (one entry per file).
// Regenerate: npm run gen:komoditas

export const KOMODITAS: { id: string; label: string; kelompok: string }[] = [
  { id: "chili_hijau_besar", label: "Cabai Hijau Besar", kelompok: "Cabai" },
  { id: "chili_merah_besar", label: "Cabai Merah Besar", kelompok: "Cabai" },
  { id: "chili_merah_keriting", label: "Cabai Merah Keriting", kelompok: "Cabai" },
  { id: "chili_rawit", label: "Cabai Rawit Merah", kelompok: "Cabai" },
  { id: "cucumber_baby", label: "Timun Baby", kelompok: "Timun" },
  { id: "cucumber_lokal", label: "Timun Lokal", kelompok: "Timun" },
  { id: "tomato_beef", label: "Tomat Beef", kelompok: "Tomat" },
  { id: "tomato_ceri", label: "Tomat Ceri", kelompok: "Tomat" },
  { id: "tomato_merah", label: "Tomat Merah", kelompok: "Tomat" },
  { id: "tomato_sayur", label: "Tomat Sayur", kelompok: "Tomat" },
  { id: "carrot", label: "Wortel", kelompok: "Wortel" },
];
