// AUTO-GENERATED by scripts/gen-metrik-model.mjs — do NOT edit by hand.
// Source of truth: ai_engine/outputs/metrik_yolo2.json, hasil
// `python ai_engine/eval_yolo2_cls.py` atas split val di datasets/yolo2_ready.
// Regenerate: npm run gen:metrik

export interface MetrikKomoditas {
  /** Kunci komoditas — nama tampilnya diambil dari kamus i18n, bukan dari sini. */
  id: string;
  arsitektur: string;
  /** Jumlah gambar pada split validasi — konteks wajib untuk membaca persentase. */
  jumlahVal: number;
  /** Pecahan 0–1. Diformat saat render supaya ikut bahasa pembaca. */
  akurasi: number;
  /** Rata-rata makro antar kelas (sehat/busuk), bukan salah satu kelas saja. */
  f1: number;
  presisi: number;
  recall: number;
  /** Nama kelas apa adanya dari model (`busuk`, `sehat`). */
  kelas: string[];
}

/** Tanggal evaluasi (ISO 8601, UTC) — ditampilkan apa adanya di kartu model. */
export const METRIK_DIEVALUASI_PADA = "2026-08-02T09:42:39+00:00";

export const METRIK_KOMODITAS: MetrikKomoditas[] = [
  {
    id: "tomato",
    arsitektur: "yolo11n-cls",
    jumlahVal: 200,
    akurasi: 0.975,
    f1: 0.975,
    presisi: 0.9755,
    recall: 0.975,
    kelas: ["busuk","sehat"],
  },
  {
    id: "cucumber",
    arsitektur: "yolo11n-cls",
    jumlahVal: 112,
    akurasi: 0.9821,
    f1: 0.9821,
    presisi: 0.9821,
    recall: 0.9821,
    kelas: ["busuk","sehat"],
  },
  {
    id: "carrot",
    arsitektur: "yolo11n-cls",
    jumlahVal: 110,
    akurasi: 1,
    f1: 1,
    presisi: 1,
    recall: 1,
    kelas: ["busuk","sehat"],
  },
  {
    id: "chili",
    arsitektur: "yolo11n-cls",
    jumlahVal: 16,
    akurasi: 0.8125,
    f1: 0.8117,
    presisi: 0.8175,
    recall: 0.8125,
    kelas: ["busuk","sehat"],
  },
];
