-- PANTAS — Migrasi 0006: Persistensi Rute Konsolidasi (F-51)
--
-- Perencana di /admin/rute sebelumnya murni kalkulator klien: admin memilih
-- titik, heuristik nearest-neighbour berjalan, hasilnya hilang saat refresh.
-- Migrasi ini melengkapi tabel `rute`/`rute_item` agar rencana bisa disimpan,
-- dirujuk petani ("Penjemputan Anda tergabung dalam Rute #12"), dan ikut
-- terhitung di view `dampak_agregat`.

-- 1. Nomor rute yang terbaca manusia -------------------------------------
-- `rute.id` berupa uuid, tidak bisa dikutip di layar petani. `nomor` adalah
-- identitas urut yang dipakai UI; uuid tetap kunci relasional.
alter table public.rute
  add column if not exists nomor bigint generated by default as identity;

create unique index if not exists idx_rute_nomor on public.rute(nomor);

-- 2. Perkiraan tiba per perhentian ---------------------------------------
-- Dihitung perencana dari urutan kunjungan + kecepatan rata-rata + waktu muat,
-- lalu disimpan supaya petani melihat jam yang sama dengan yang dilihat admin.
alter table public.rute_item
  add column if not exists perkiraan_tiba timestamptz;

-- 3. Muatan tidak boleh melebihi kapasitas kendaraan ----------------------
-- Kolom `kapasitas_kg` sudah ada sejak 0004 tapi tidak pernah ditegakkan.
-- Trigger menolak penambahan item yang membuat total berat melewati kapasitas.
create or replace function public.cek_kapasitas_rute()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  total_kg   numeric;
  kapasitas  numeric;
begin
  select r.kapasitas_kg into kapasitas
  from public.rute r
  where r.id = new.rute_id;

  select coalesce(sum(o.berat_kg), 0) into total_kg
  from public.rute_item ri
  join public.pengiriman s on s.id = ri.pengiriman_id
  join public.orders o     on o.id = s.order_id
  where ri.rute_id = new.rute_id;

  if kapasitas is not null and total_kg > kapasitas then
    raise exception
      'Muatan rute % kg melampaui kapasitas kendaraan % kg',
      total_kg, kapasitas
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_cek_kapasitas_rute on public.rute_item;
create constraint trigger trg_cek_kapasitas_rute
  after insert or update on public.rute_item
  deferrable initially deferred
  for each row execute function public.cek_kapasitas_rute();

-- 4. Kebijakan tulis — hanya admin ---------------------------------------
-- 0004 hanya memberi policy SELECT, sehingga admin tidak pernah bisa menyimpan.
-- Konsolidasi lintas petani adalah keputusan koperasi, jadi tulis dikunci ke
-- peran admin (bukan petani/pembeli yang hanya melihat rutenya sendiri).
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.peran = 'admin'
  );
$$;

drop policy if exists "Admin membuat rute" on public.rute;
create policy "Admin membuat rute"
  on public.rute for insert
  with check (public.is_admin());

drop policy if exists "Admin mengubah rute" on public.rute;
create policy "Admin mengubah rute"
  on public.rute for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admin menghapus rute draf" on public.rute;
create policy "Admin menghapus rute draf"
  on public.rute for delete
  using (public.is_admin() and status = 'draf');

drop policy if exists "Admin membuat rute item" on public.rute_item;
create policy "Admin membuat rute item"
  on public.rute_item for insert
  with check (public.is_admin());

drop policy if exists "Admin mengubah rute item" on public.rute_item;
create policy "Admin mengubah rute item"
  on public.rute_item for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admin menghapus rute item" on public.rute_item;
create policy "Admin menghapus rute item"
  on public.rute_item for delete
  using (public.is_admin());

-- 5. Indeks lookup arah balik --------------------------------------------
-- Layar logistik petani bertanya "pengiriman ini masuk rute mana?", arah yang
-- berlawanan dengan idx_rute_item_rute di 0004.
create index if not exists idx_rute_item_pengiriman
  on public.rute_item(pengiriman_id);
